// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "openaiKey": string;
      "claudeKey": string;
      "trackArxiv": boolean;
      "trackPubmed": boolean;
      "relevanceThreshold": number;
      "shortcutKey": string;
    };
  }
}
